### ISSUE TITLE
Epic: Agregar test

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#16]
En orden de ir probando nuestro código hay que agregar test para probar el funcionamiento de nuestro sitio

**Comment by gueroverde** [comment]
Estoy trabajando en agregar test al registro del sitio:

- [x] cuando no es un email
- [x] cuando es un mail banneado a traves de emailChecker
- [ ] cuando es un mail duplicado
- [ ] cuando se registra mostrar el flash message en la pagina
- [ ] Cuando se registra validar el envio del email

La branch donde estoy trabajando esto es https://github.com/phpmx/phpmexico/tree/feature/test-user-sign-up
